config/routes.rb
Rails.application.routes.draw do
  resources :tasks, only: [:index, :create, :destroy]

  root 'tasks#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def create
    @task = Task.create(task_params)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_task.html.erb
<li id="task-<%= task.id %>">
<%= task.name %>: <%= task.description %> | <strong><%= task.status %></strong>

<%= link_to 'delete', task_path(task), method: 'delete', data: {confirm: "Are you sure?"}, remote: true %>
</li>

app/views/tasks/create.js.erb
$('#task-list').prepend("<%= j render @task %>");

app/views/tasks/destroy.js.erb
$('#task-<%= @task.id %>').fadeOut();

app/views/tasks/index.html.erb
<h1>Welcome to Task App!</h1>

<h3>All the tasks:</h3>
<ul id="task-list">
  <%= render @tasks %>
</ul>

<%= form_for Task.new, remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :status %>
  <%= f.text_field :status %>

  <%= f.submit %>
<% end %>